export { listJuntaCarpetaExpedientes } from './listJuntaCarpetaExpedientes'
export { listJuntaCarpetaNotifications } from './listJuntaCarpetaNotifications'
export { listJuntaDebts } from './listJuntaDebts'
export { listJuntaDocuments } from './listJuntaDocuments'
export { listJuntaFees } from './listJuntaFees'
export { listJuntaPayments } from './listJuntaPayments'
export { listJuntaRepresentedExpedientes } from './listJuntaRepresentedExpedientes'
export { acceptJuntaCarpetaNotification } from './notifications/acceptJuntaCarpetaNotification'
export { downloadJuntaCarpetaNotification } from './notifications/downloadJuntaCarpetaNotification'
export type { CarpetaAcceptance } from './notifications/types/CarpetaAcceptance'
export type { CarpetaAcceptanceRequest } from './notifications/types/CarpetaAcceptanceRequest'
export type { CarpetaDownload } from './notifications/types/CarpetaDownload'
export type { GobexRecord } from './types/GobexRecord'
