export { appearAtNotification } from './aeat/appearance/appearAtNotification'
export { emitCensalCertificate } from './aeat/census/emitCensalCertificate'
export type { CensalCertificateRequest } from './aeat/census/types/CensalCertificateRequest'
export type { CensalCertificateResult } from './aeat/census/types/CensalCertificateResult'
export { emitComplianceCertificate } from './aeat/compliance/emitComplianceCertificate'
export type { ComplianceCertificateRequest } from './aeat/compliance/types/ComplianceCertificateRequest'
export type { ComplianceCertificateResult } from './aeat/compliance/types/ComplianceCertificateResult'
export type { CompliancePurpose } from './aeat/compliance/types/CompliancePurpose'
export { sweepAeatDebts } from './aeat/debts/sweepAeatDebts'
export type { AeatDebtReport } from './aeat/debts/types/AeatDebtReport'
export { listAeatFilings } from './aeat/filings/listAeatFilings'
export type { AeatFiling } from './aeat/filings/types/AeatFiling'
export type { AeatFilingsReport } from './aeat/filings/types/AeatFilingsReport'
export type { FilingsQuery } from './aeat/filings/types/FilingsQuery'
export { listAeatInformatives } from './aeat/informatives/listAeatInformatives'
export type { InformativeFiling } from './aeat/informatives/types/InformativeFiling'
export type { InformativesQuery } from './aeat/informatives/types/InformativesQuery'
export type { InformativesReport } from './aeat/informatives/types/InformativesReport'
export { generatePaymentLetter } from './aeat/paymentLetter/generatePaymentLetter'
export { listAeatPayments } from './aeat/payments/listAeatPayments'
export type { AeatPayment } from './aeat/payments/types/AeatPayment'
export type { AeatPaymentsReport } from './aeat/payments/types/AeatPaymentsReport'
export { changeTaxAddress } from './aeat/taxAddress/changeTaxAddress'
export { loadCertificateIdentity } from './certificate/loadCertificateIdentity'
export type { CertificateIdentity } from './certificate/types/CertificateIdentity'
export { requestRiskReport } from './cirbe/report/requestRiskReport'
export { readCirbeStatus } from './cirbe/status/readCirbeStatus'
export { followAutoSubmitForms } from './clave/followAutoSubmitForms'
export { downloadNotificationDocuments } from './dehu/documents/downloadNotificationDocuments'
export type { DocumentsQuery } from './dehu/documents/types/DocumentsQuery'
export type { DocumentsResult } from './dehu/documents/types/DocumentsResult'
export type { DownloadedDocument } from './dehu/documents/types/DownloadedDocument'
export { listNotifications } from './dehu/notifications/listNotifications'
export type { ListQuery } from './dehu/notifications/types/ListQuery'
export type { Notification } from './dehu/notifications/types/Notification'
export * from './gobex/index'
export { htmlToText } from './html/htmlToText'
export { parseFirstForm } from './html/parsers/parseFirstForm'
export { parseForms } from './html/parsers/parseForms'
export type { HtmlForm } from './html/types/HtmlForm'
export { unescapeHtml } from './html/unescapeHtml'
export { createHttpClient } from './http/createHttpClient'
export { postForm } from './http/postForm'
export type { HttpClient } from './http/types/HttpClient'
export type { HttpRequestOptions } from './http/types/HttpRequestOptions'
export type { HttpResponse } from './http/types/HttpResponse'
export { listOargtReceipts } from './oargt/receipts/listOargtReceipts'
export type { AmountToday } from './oargt/receipts/types/AmountToday'
export type { ListOargtReceiptsOptions } from './oargt/receipts/types/ListOargtReceiptsOptions'
export type { OargtReceiptsResult } from './oargt/receipts/types/OargtReceiptsResult'
export type { Receipt } from './oargt/receipts/types/Receipt'
export * from './placsp/index'
export * from './rolece/index'
export { readLastBenefit } from './sepe/benefits/readLastBenefit'
export type { LastBenefit } from './sepe/benefits/types/LastBenefit'
export { emitSituationCertificate } from './sepe/certificates/emitSituationCertificate'
export type { SituationCertificateResult } from './sepe/certificates/types/SituationCertificateResult'
export { loginWithCertificate as loginSepeWithCertificate } from './sepe/session/loginWithCertificate'
export { signPdf } from './signing/pades/signPdf'
export { signPdfFile } from './signing/pades/signPdfFile'
export { signPkcs1Sha256 } from './signing/signPkcs1Sha256'
export { signXml } from './signing/xades/signXml'
export { signXmlFile } from './signing/xades/signXmlFile'
export { listStaExpedientes } from './sta/listStaExpedientes'
export { listStaNotifications } from './sta/listStaNotifications'
export { listStaRegistrations } from './sta/listStaRegistrations'
export type { StaExpediente } from './sta/types/StaExpediente'
export type { StaNotification } from './sta/types/StaNotification'
export type { StaPortal } from './sta/types/StaPortal'
export type { StaRegistration } from './sta/types/StaRegistration'
export type { StaRole } from './sta/types/StaRole'
export { emitEmploymentAtDate } from './tgss/affiliation/emitEmploymentAtDate'
export { emitIdentityData } from './tgss/affiliation/emitIdentityData'
export { emitSocialSecurityNumber } from './tgss/affiliation/emitSocialSecurityNumber'
export { emitVidaLaboral } from './tgss/affiliation/emitVidaLaboral'
export { emitWorkerSituation } from './tgss/affiliation/emitWorkerSituation'
export type { AffiliationReportResult } from './tgss/affiliation/types/AffiliationReportResult'
export type { EmploymentAtDateResult } from './tgss/affiliation/types/EmploymentAtDateResult'
export type { VidaLaboralQuery } from './tgss/affiliation/types/VidaLaboralQuery'
export type { VidaLaboralResult } from './tgss/affiliation/types/VidaLaboralResult'
export { attachToExpediente } from './tgss/attachments/attachToExpediente'
export { certificateKinds } from './tgss/certificates/certificateKinds'
export { emitUpToDateCertificate } from './tgss/certificates/emitUpToDateCertificate'
export type { CertificateKind } from './tgss/certificates/types/CertificateKind'
export type { TgssCertificateResult } from './tgss/certificates/types/TgssCertificateResult'
export { emitContributionsReport } from './tgss/contributions/emitContributionsReport'
export type { ContributionRow } from './tgss/contributions/types/ContributionRow'
export type { ContributionsPage } from './tgss/contributions/types/ContributionsPage'
export type { ContributionsQuery } from './tgss/contributions/types/ContributionsQuery'
export type { ContributionsReportResult } from './tgss/contributions/types/ContributionsReportResult'
export { parseDebtReportText } from './tgss/debt/parsers/parseDebtReportText'
export { readTgssDebt } from './tgss/debt/readTgssDebt'
export type { DebtReportKind } from './tgss/debt/types/DebtReportKind'
export type { TgssDebtResult } from './tgss/debt/types/TgssDebtResult'
export { requestDeferral } from './tgss/deferral/requestDeferral'
export * from './tgss/employer/index'
export { readFiscalCalendar } from './tools/calendar/readFiscalCalendar'
export { validateNif } from './tools/nif/validators/validateNif'
export { isConfirmed } from './write/isConfirmed'
export type { WriteResult } from './write/types/WriteResult'
